  var feature_route = {
  literacy_card: '/pages/package_feature/cognition_card/index/index',
  free_resource: '/pages/package_common/free_resources/detail/index',
  pic2doc: '/pages/print_photo_doc/index',
  preschool_course: '/pages/course/index',
  subject_course: '/pages/package_common/heart_course/index',
  kid_record: '/pages/package_preschool/record_voice/index/index',
  doc_a4: '/pages/print_doc/index/index',
  id_card: '/pages/print_doc/duplicate/index',
  invoice: '/pages/print_doc/print_invoice/print_invoice',
  _id1in: '/pages/print_id/index',
  _id2in: '/pages/print_id/index',
  _id1ins: '/pages/print_id/index',
  _id1inb: '/pages/print_id/index',
  _id2ins: '/pages/print_id/index',
  _id2inb: '/pages/print_id/index',
  _id3in: '/pages/print_id/index',
  _visa_usa: '/pages/print_id/index',
  _visa_jp: '/pages/print_id/index',
  _visa_kor: '/pages/print_id/index',
  _visa_tha: '/pages/print_id/index',
  normal_id:'/pages/print_id/index',
  pic_in6: '/pages/print_photo/photolist',
  pic_in5: '/pages/print_photo/photolist',
  lomo: '/pages/print_photo/photolist',
  pic_in7: '/pages/print_photo/photolist',
  pic_a4: '/pages/print_photo/photolist',
  balloon:'/pages/package_feature/print_balloon/index',
  photo_book:'/pages/package_feature/print_book/index',
  diy_calendar:'/pages/package_feature/print_calendar/index',
  wood_calendar:'/pages/package_feature/print_calendar/index',
  name_sticker:'/pages/package_feature/print_name/index',
  postcard:'/pages/package_feature/print_postcard/index',
  photo_sticker:'/pages/package_feature/print_sticker/index',
  mini_album:'/pages/package_feature/print_thumb_album/index',
  share_folder_pic_5in: '/pages/package_feature/share_folder/index',
  english_memory_write: '/pages/package_feature/memory_write/english/index',
  chinese_memory_write: '/pages/package_feature/memory_write/chinese/index',
  kousuan:'/pages/package_feature/kousuan/index',
  baobeicepin:'/pages/package_preschool/evaluation/index',
  link:'/pages/package_feature/print_link/index',
  stage_report: '/pages/package_subject/stage_report/index/index',
  exam_paper_report: '/pages/package_subject/exam_paper_report/index/index',
  weakness_exercise: '/pages/package_subject/weakness_exercise/index/index',
  sync_learn: '/pages/package_subject/sync_learn/learn_content/index',
  daily_practice: '/pages/package_preschool/exercise_day/exercises/exercises',
  testimonial: '/pages/package_preschool/exercise_day/certificate/index',
  copybook:'/pages/package_feature/copy_book/index',
  xuekewang_paper:'/pages/package_subject/evaluate_exam/testpaper/index',
  errorbook_list:'/pages/package_subject/super_errorbook/errorbook/index',
  error_book:'/pages/package_feature/error_book/index',
  photo_answer:'/pages/package_feature/error_book/photo_anwser_intro',
  preschool_content:'/pages/package_common/common_content/index',
  word_pdf:'/pages/package_feature/print_speed/intro',
  shareFile:'/pages/package_feature/share_folder/index',
  qdnl:'/pages/package_preschool/growth_plan/list/index'
}

module.exports = {
  feature_route: feature_route,
}
